name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name : install pip dependencies 
        run: pip install -r requirements.txt && sudo npm install -g aws-cdk
      - name: Synth stack
        run: cd aws_stepfunction_cdk && cdk synth
      - name: Deploy stack
        run: cd aws_stepfunction_cdk &&  cdk deploy --all --require-approval never   