name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          node-version: "14"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          working-directory: ./aws_stepfunction_cdk/
      - run: pip install -r requirements.txt
      - name: Synth stack
        run: cd my-aws-cdk-app && yarn cdk synth
      - name: Deploy stack
        run: cd my-aws-cdk-app && yarn cdk deploy --all --require-approval never

        run: |

          pwd

          npm ci

      - name: cdk synth

        id: synth

        run: npx cdk synth

      - name: cdk deploy

        id: cdk

        run: npx cdk deploy --require-approval never
